changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - dependabot
      - pre-commit-ci
  categories:
    - title:  API changes
      labels: refactor, ...
    - title: Enhancements
      labels:
        - enhancement
    - title: Bug Fixes
      labels:
        - bug
    - title: Deprecations
      labels:
        - ...
    - title: Refactor
      labels:
        - refactor
    - title: Documentation
      labels:
        - documentation
    - title: Other Changes
      labels:
        - "*"
