changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - dependabot
      - pre-commit-ci
  categories:
    - title: Bug Fixes
      labels:
        - bug
    - title: Enhancements
      labels:
        - enhancement
    - title: Refactor
      labels:
        - refactor
    - title: Preprocessing
      labels:
        - preprocessing
    - title: Documentation
      labels:
        - documentation
    - title: Refactor
      labels:
        - refactor
    - title: Other Changes
      labels:
        - "*"
