codecov:
  notify:
    after_n_builds: 6
coverage:
  range: 50..95
  round: nearest
  precision: 1
  status:
    project:
      default:
        threshold: 2%
    patch:
      default:
        threshold: 2%
        target: 80%
  ignore:
    - "tests/*"
comment:
  layout: "reach, diff, files"
  behavior: once
  after_n_builds: 6
  require_changes: true
