---
name: momepy_env
channels:
  - conda-forge
dependencies:
  - python
  - esda
  - geopandas
  - inequality
  - jupyter
  - libpysal
  - mapclassify
  - matplotlib
  - neatnet
  - networkx
  - numba
  - osmnx
  - pandas
  - rioxarray
  - shapely
  - tqdm
  - xvec
