name: test
channels:
  - conda-forge
dependencies:
  - python=3.8
  - geopandas
  - libpysal
  - networkx
  - tqdm
  - pytest
  - pytest-cov
  - codecov
  - mapclassify
  - pip
  - osmnx
  - black
  - nose
  - inequality
  - pygeos
  - pip:
      - git+https://github.com/geopandas/geopandas.git
      - git+https://github.com/pysal/libpysal.git
      - git+https://github.com/networkx/networkx.git
      - git+https://github.com/pygeos/pygeos.git
