name: Sumbit question
description: Ask a general question about momepy
labels: [question]
body:
  - type: textarea
    id: question
    attributes:
      label: Your question
      description: |
        Please make sure that:

        - You have searched the [StackOverflow](https://stackoverflow.com/) and [GIS StackExchange](https://gis.stackexchange.com/questions/) for similar questions.

        - You have asked your usage related question on [StackOverflow](https://stackoverflow.com) or [GIS StackExhange](https://gis.stackexchange.com).

        If you'd still like to submit a question, please read [this guide](
        https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your question.
      placeholder: |
        I don't understand how XXX should be used...
        I am not sure what is YYY actually measuring. Can you explain?

        ```python
        # Your code here, if applicable

        ```
    validations:
      required: true
