name: test
channels:
  - conda-forge
dependencies:
  - python=3.8
  - geopandas
  - libpysal
  - networkx
  - tqdm
  - pytest
  - pytest-cov
  - codecov
  - pip
  - pip:
    - black
    - nose
    - mapclassify==2.0.1
    - inequality
