name: test
channels:
  - conda-forge
dependencies:
  - python=3.7
  - geopandas
  - libpysal
  - networkx
  - tqdm
  - pytest
  - pytest-cov
  - codecov
  - pysal
  - pip
  - pip:
    - black
    - nose
    - git+https://github.com/geopandas/geopandas.git
    - git+https://github.com/pysal/libpysal.git
    - git+https://github.com/networkx/networkx.git
