name: test
channels:
  - conda-forge
dependencies:
  - python=3.13
  - geopandas
  - inequality
  - libpysal
  - mapclassify
  - networkx
  - osmnx
  - packaging
  - pandas
  - shapely
  - esda
  - tqdm
  - numba
  # testing
  - codecov
  - pytest
  - pytest-cov
  # user guide
  - inequality
  - jupyter
  - matplotlib
  - osmnx
  - clustergram
  - bokeh
  - geopy
  - ipywidgets
  - Iprogress
  - matplotlib
  - numpydoc
  - pydata-sphinx-theme
  - nbsphinx
  - myst-parser
  - pip
  - pip:
    - sphinx_copybutton
    - sphinx-gallery
    - sphinxext-rediraffe
    - sphinxcontrib.bibtex
    - git+https://github.com/geopandas/geopandas.git
