name: momepy_docs
channels:
    - conda-forge
dependencies:
    - sphinx_bootstrap_theme=0.6.4
    - python=3.7
    - geopandas
    - libpysal
    - networkx
    - tqdm
    - mapclassify
    - momepy
    - matplotlib
    - rtree
    - osmnx
    - pip:
        - inequality
        - sphinxcontrib.bibtex
        - numpydoc
