---
name: Build Docs

on:  # yamllint disable-line rule:truthy
  push:
    branches: [main]
    tags:
      - "v*"
  pull_request:
    branches:
      - "*"
  workflow_dispatch:
    inputs:
      version:
        description: Manual Doc Build
        default: run-doc-build
        required: false
jobs:
  docs:
    name: Build & push docs
    runs-on: ${{ matrix.os }}
    timeout-minutes: 90
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        environment-file: [ci/envs/314-latest.yaml]
        experimental: [false]
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup micromamba
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: ${{ matrix.environment-file }}
          micromamba-version: "latest"

      - name: Install package
        run: pip install . --no-deps

      - name: Make docs
        run: cd docs; make html

      - name: Zip documentation
        if: ${{ github.event_name == 'pull_request' }}
        run: zip docs_artifact.zip docs/build/html -r

      - name: Upload artifact
        if: ${{ github.event_name == 'pull_request' }}
        uses: actions/upload-artifact@v7
        with:
          name: docs_artifact
          path: docs_artifact.zip
