name: macOS CI

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 3
      matrix:
        os: [macOS-latest]
        envs: [ci/37-mc.yaml]

    steps:
    - uses: actions/checkout@v1
    - name: Build environment
      run: |
        pushd .
        cd $HOME
        eval "$($CONDA/bin/conda shell.bash hook)"
        conda activate

        conda config --set always_yes yes --set changeps1 no
        conda update -q conda
        conda config --add channels conda-forge
        conda config --set channel_priority strict
        popd
        conda env create --file="${{ matrix.envs }}"
        conda activate test
        python setup.py install
    - name: Conda list
      run: |
        eval "$($CONDA/bin/conda shell.bash hook)" && conda activate test
        conda list
    - name: Run tests
      run: |
        eval "$($CONDA/conda shell.bash hook)" && conda activate test
        pytest -v tests
